import { z } from "zod";

/** Contract version carried by every file. Bump only for a breaking change. */
export const Version = z.literal(1);

/** UUID as generated by the mod: version 4 with the RFC 9562 variant bits. */
export const Uuid = z.uuid();

/**
 * Wall-clock time. The game only exposes local time, so the mod writes RFC 3339 with the local
 * offset when it can and without one otherwise (PLAN_REVIEW.md C2). The bridge normalizes to UTC.
 */
export const RealTimestamp = z.iso.datetime({ offset: true, local: true });

/** `environment.currentMonotonicDay` (PLAN_REVIEW.md C1). */
export const GameDay = z.int().min(0);

/** Minute of the in-game day. */
export const MinuteOfDay = z.int().min(0).max(1439);

/** FS farm id. 0 means no farm (spectator or a system event). */
export const FarmId = z.int().min(0).max(255);

/** `vehicle:getUniqueId()`, which persists in the savegame (PLAN_REVIEW.md C4). */
export const VehicleId = z.string().min(1).max(128);

/** AI job id. Unique within one game session only (PLAN_REVIEW.md C4). */
export const JobId = z.string().min(1).max(64);

/** FS fill type name, for example `WHEAT` or `DIESEL`. */
export const FillTypeName = z.string().min(1).max(64);

export const Percent = z.number().min(0).max(100);

/** World position in meters; `heading` in degrees, 0 = north, clockwise. */
export const Position = z.object({
  x: z.number(),
  y: z.number().optional(),
  z: z.number(),
  heading: z.number().min(0).lt(360).optional(),
});

/** One fill unit. `capacity` is null when the game reports it as unlimited. */
export const FillLevel = z.object({
  fillType: FillTypeName.nullable(),
  level: z.number().min(0),
  capacity: z.number().min(0).nullable(),
});
