// Builds the phone page the bridge serves into one self-contained HTML string, written to
// generated/page.ts. The page must work with no internet (the phone only reaches the bridge), so
// the script and the styles are inlined. React resolves to preact/compat, which keeps the page
// small. The output is committed; test/page.test.ts fails when it is stale.
//
//   pnpm --filter @farmlink/live-ui run build

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { build, transform } from "esbuild";

const root = fileURLToPath(new URL("../", import.meta.url));
export const PAGE_MODULE = `${root}generated/page.ts`;

const ICON_SVG =
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">' +
  '<rect width="64" height="64" rx="14" fill="#3f7d2f"/>' +
  '<circle cx="32" cy="34" r="17" fill="none" stroke="#fff" stroke-width="6"/>' +
  '<circle cx="32" cy="34" r="5" fill="#fff"/></svg>';

async function bundleScript(): Promise<string> {
  const result = await build({
    absWorkingDir: root,
    entryPoints: ["src/page/main.tsx"],
    bundle: true,
    write: false,
    format: "iife",
    minify: true,
    target: ["es2020", "safari15", "chrome90", "firefox90"],
    jsx: "automatic",
    jsxImportSource: "preact",
    alias: { react: "preact/compat", "react-dom": "preact/compat" },
    legalComments: "none",
    charset: "utf8",
    logLevel: "silent",
  });
  const output = result.outputFiles[0];
  if (!output) throw new Error("esbuild produced no output");
  // A literal "</script" inside the bundle would end the inline script early.
  return output.text.trim().replace(/<\/script/gi, "<\\/script");
}

async function minifyStyles(): Promise<string> {
  const css = readFileSync(`${root}src/page/styles.css`, "utf8");
  const result = await transform(css, {
    loader: "css",
    minify: true,
    target: ["safari15", "chrome90", "firefox90"],
  });
  return result.code.trim();
}

export async function buildPageHtml(): Promise<string> {
  const [script, styles] = await Promise.all([bundleScript(), minifyStyles()]);
  const icon = `data:image/svg+xml,${encodeURIComponent(ICON_SVG)}`;
  return [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">',
    '<meta name="referrer" content="no-referrer">',
    '<meta name="theme-color" content="#3f7d2f">',
    '<meta name="mobile-web-app-capable" content="yes">',
    '<meta name="apple-mobile-web-app-capable" content="yes">',
    '<meta name="apple-mobile-web-app-title" content="FarmLink">',
    "<title>FarmLink Live</title>",
    `<link rel="icon" href="${icon}">`,
    `<style>${styles}</style>`,
    "</head>",
    "<body>",
    '<div id="root"></div>',
    `<script>${script}</script>`,
    "</body>",
    "</html>",
    "",
  ].join("\n");
}

export function pageModule(html: string): string {
  return [
    "// Generated by scripts/build-page.ts from src/; do not edit. Rebuild with",
    "//   pnpm --filter @farmlink/live-ui run build",
    "",
    `export const PAGE_HTML = ${JSON.stringify(html)};`,
    "",
  ].join("\n");
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const html = await buildPageHtml();
  writeFileSync(PAGE_MODULE, pageModule(html));
  console.log(
    `wrote generated/page.ts: ${(Buffer.byteLength(html) / 1024).toFixed(1)} KiB of HTML`,
  );
}
